### ISSUE TITLE
ne pas afficher les adresses mails secondaires

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/roundcube_laclasse_addressbook#4]
Chaque enseignant peut choisir d'avoir une adresse académique, personnelle ou Laclasse.com comme adresse principale. Par contre Mme Kerioui nous signale  que  lorsque le nom de quelqu'un est saisi comme destinataire d'un message toutes ses adresses mail apparaissent. Elle l'avait constaté pour les enseignants et leur avais conseillé de modifier cela dans leur profil en ne laissant apparaître que l'adresse de la classe.com. Elle demande si ce serait possible de ne pas afficher les adresses mails secondaires.

**Comment by dlacroix** [comment]
Les adresses emails secondaires n'ont jamais été affichées.
